Create files to support NSMovie and NSMovieView
gnustep/libs-gui pull request #144
Opened 2022-03-20 23:34 UTC by gcasa

implementation for NSMovie and NSMovieView.

2023-01-13 16:17 UTC, fredkiefer commented on ChangeLog
> +>>>>>>> e0012349f6df6895f736de1f158c52116fce7fc1
This line seems to be a leftover from a failed merge.

2023-01-13 16:19 UTC, fredkiefer commented on Source/NSMovie.m
> +        }
you need to return `nil` here and not `self`.

2025-05-26 15:43 UTC, gcasa commented on Source/NSMovie.m
> +        }
Obsolete.

2025-05-26 15:43 UTC, gcasa commented on ChangeLog
> +>>>>>>> e0012349f6df6895f736de1f158c52116fce7fc1
Obsolete.

2025-05-29 20:04 UTC, gcasa commented
For some reason the sound is a little choppy, I am trying to address this.  In the meantime I am going to work on implementing the other features of this class.

2025-06-04 14:20 UTC, gcasa commented
Sound seems to be working now, apparently the sample rate was misconfigured.   I am working on implementing the video looping settings as well as other settings.  The methods for editing are going to be left unimplemented as I am not certain how to do those yet.

2025-06-10 21:27 UTC, gcasa commented
I am making this ready for review so that, perhaps, people who are more familiar with avcodec et. al. might be able to help me improve this.

2025-06-11 19:54 UTC, gcasa commented
Just as a note NSSound is not fast enough to handle the samples being fed, so it was necessary to create the audio player.

2025-07-29 01:54 UTC, gcasa commented
I think this is the best I can do on this.  @fredkiefer could you take a look and see what else you might be able to see.  This is certainly better than we have at the moment (nothing) and I think it would be useful for others to take a look and try to improve this.

2025-07-29 01:57 UTC, gcasa commented
<img width="1300" height="795" alt="screen_grab" src="https://github.com/user-attachments/assets/b031f2e9-7b7d-4535-8fde-5ff5a4495141" />

The sound is now working and I have added a set of (default) controls.

2025-08-02 11:00 UTC, fredkiefer requested changes
I only got halfway through in reviewing this code but I think this already gives you enough to further work on your code.

2025-08-02 11:00 UTC, fredkiefer commented on Headers/AppKit/NSMovieView.h
> +  BOOL _playing;
Have you considered putting this value into one of the reserved bit on the following flag array?

2025-08-02 11:00 UTC, fredkiefer commented on Source/GSAVUtils.m
> +  NSData *data = [NSData dataWithBytes:packet->data length:packet->size];
Could you please leave a space after the colon? I think this is more readable and still the more common GNUstep coding style.

2025-08-02 11:00 UTC, fredkiefer commented on Source/GSAudioPlayer.m
> +  ao_shutdown();
This only works if this class is used as a singleton. I am not sure whether this is the case or not.

2025-08-02 11:00 UTC, fredkiefer commented on Source/GSAudioPlayer.m
> +      NSLog(@"[GSAudioPlayer] WARNING: swr_init returned 0");
Why is there now `return` here?

2025-08-02 11:00 UTC, fredkiefer commented on Source/GSAudioPlayer.m
> +  _audioCodecCtx = avcodec_alloc_context3(audioCodec);
if this method gets called a second time we will leak memory.

2025-08-02 11:00 UTC, fredkiefer commented on Source/GSAudioPlayer.m
> +  NSLog(@"[GSAudioPlayer] Initializing audio: %d Hz, %d channels, buffer size: %d bytes",
This probably should be a debug log.

2025-08-02 11:00 UTC, fredkiefer commented on Source/GSAudioPlayer.m
> +	@synchronized (_audioPackets)
I think this is only supported by clang. It would be nice to get this code running with gcc is well. Otherwise we need to protect this code in the Makefile so it won't be used when compiling with gcc.

2025-08-02 11:00 UTC, fredkiefer commented on Source/GSAudioPlayer.m
> +	    NSLog(@"[GSAudioPlayer] Audio playback started | Timestamp: %ld", audioStartTime);
Again this should be a debug log.

2025-08-02 11:00 UTC, fredkiefer commented on Source/GSAudioPlayer.m
> +		fprintf(stderr, "[GSAudioPlayer] Audio clock: %ld | PTS: %ld | Samples: %ld | Timing error: %ld us\n",
Why `fprintf` and not NSLog, or rather NSDebugLog?

2025-08-02 11:00 UTC, fredkiefer commented on Source/GSAudioPlayer.m
> +  _volume = volume;
Why doesn't this method set _muted?

2025-08-02 11:00 UTC, fredkiefer commented on Source/GSAudioPlayer.m
> +      uint8_t *outBuf = (uint8_t *) malloc(outBytes);
We should think about keeping a buffer for a longer time. Most samples will require a buffer with the same size and we could reuse that.

2025-08-02 11:00 UTC, fredkiefer commented on Source/GSMovieView.h
> +  BOOL _running; // is the loop currently running...
Doesn't this duplicate the _playing variable from the super class?

2025-08-02 11:00 UTC, fredkiefer commented on Source/NSMovie.m
> +      _tmp = YES;
It seems like this variable is only ever set but never read.

2025-08-02 17:49 UTC, gcasa commented on Headers/AppKit/NSMovieView.h
> +  BOOL _playing;
Hey, Fred!  I hope all is well.  I hadn't considered that, but it is certainly a good idea.

2025-08-02 17:49 UTC, gcasa commented on Source/GSAVUtils.m
> +  NSData *data = [NSData dataWithBytes:packet->data length:packet->size];
yes, absolutely.

2025-08-02 21:02 UTC, gcasa commented on Source/GSAudioPlayer.m
> +      NSLog(@"[GSAudioPlayer] WARNING: swr_init returned 0");
The documentation indicates that this is not a critical issue.   There are instances where this works just fine.

2025-08-02 21:08 UTC, gcasa commented on Source/GSAudioPlayer.m
> +  ao_shutdown();
I believe this is okay as ao_shutdown() is process isolated.   So since I am calling ao_initialize() earlier in the process it should be okay.

2025-08-02 21:10 UTC, gcasa commented on Source/GSAudioPlayer.m
> +		fprintf(stderr, "[GSAudioPlayer] Audio clock: %ld | PTS: %ld | Samples: %ld | Timing error: %ld us\n",
This is printing out every frame, so it's probably a bit more than is needed.  I likely need to turn this logging into a DebugLog instead of doing it like this.  It was helping me to monitor frames and synchronization.

2025-08-02 22:06 UTC, gcasa commented on Source/GSAudioPlayer.m
> +  _volume = volume;
Done.

2025-08-02 22:26 UTC, gcasa commented on Source/NSMovie.m
> +      _tmp = YES;
I now have it deleting the temporary file if it exists.

2025-08-02 22:35 UTC, gcasa commented on Source/GSMovieView.h
> +  BOOL _running; // is the loop currently running...
Fixed.

2025-08-02 23:08 UTC, gcasa commented on Source/GSAudioPlayer.m
> +  _audioCodecCtx = avcodec_alloc_context3(audioCodec);
Added an if to prevent this.

2025-08-02 23:09 UTC, gcasa commented on Source/GSAudioPlayer.m
> +		fprintf(stderr, "[GSAudioPlayer] Audio clock: %ld | PTS: %ld | Samples: %ld | Timing error: %ld us\n",
I'm using NSDebugLog.  I have less debugging to do on this at the moment, and the frame numbers are also output on the statusField.

2025-08-02 23:10 UTC, gcasa commented on Source/GSAudioPlayer.m
> +      uint8_t *outBuf = (uint8_t *) malloc(outBytes);
Agreed.

2025-08-02 23:56 UTC, gcasa commented on Source/GSAudioPlayer.m
> +      uint8_t *outBuf = (uint8_t *) malloc(outBytes);
Done.

2025-08-03 03:12 UTC, gcasa commented
@fredkiefer Take a look at the updates.  Thanks for reviewing the code.

2025-08-03 18:54 UTC, gcasa commented
I had to revert some of the previous changes.  Back to fac27f8.  You'll need to do a fresh checkout.

2025-08-03 21:34 UTC, gcasa commented
@fredkiefer I have addressed the issues you mentioned.  :)

2025-09-01 19:03 UTC, fredkiefer commented on ChangeLog
> +	* Source/GSib5KeyedUnarchiver.m: Add support for new keys
Something went wrong here.

2025-09-01 19:18 UTC, fredkiefer commented on Source/GSAudioPlayer.h
> +  BOOL _reachedEOF;
Why not as part of the bit field?
And "new" doesn't make much sense in the comment, as this will be the first version of the file for all others.

2025-09-01 19:21 UTC, fredkiefer commented on Source/GSAudioPlayer.m
> +  ao_shutdown();
But will it work with a process that produces two sounds at once?

2025-09-01 19:23 UTC, fredkiefer commented on Source/GSAudioPlayer.m
> +      NSDebugLog(@"Failed to open audio codec.");
Should we release _audioCodecCtx here?

2025-09-01 19:24 UTC, fredkiefer commented on Source/GSAudioPlayer.m
> +  _audioFrame = av_frame_alloc();
All these calls to allocate may return NULL, we should try to handle that.

2025-09-01 19:29 UTC, fredkiefer commented on Source/GSAudioPlayer.m
> +  snprintf(bufferSizeStr, sizeof(bufferSizeStr), "%d", bufferSize);
To me it looks like bufferSizeStr is never used.

2025-09-01 19:32 UTC, fredkiefer commented on Source/GSAudioPlayer.m
> +		dict = RETAIN([_audioPackets objectAtIndex: 0]);
Something seems wrong with the indentation.

2025-09-01 20:19 UTC, fredkiefer commented on Source/NSMovie.m
> +  return [self initWithData: movie];
This seems strange. Shouldn't you  package up the void pointer in an NSData object before passing it on?

2025-09-04 13:22 UTC, gcasa commented on ChangeLog
> +	* Source/GSib5KeyedUnarchiver.m: Add support for new keys
Not sure how that happened.  Corrected.

2025-09-04 13:31 UTC, gcasa commented on Source/GSAudioPlayer.h
> +  BOOL _reachedEOF;
Fixed.

2025-09-04 13:45 UTC, gcasa commented on Source/GSAudioPlayer.m
> +      NSDebugLog(@"Failed to open audio codec.");
Done

2025-09-04 13:53 UTC, gcasa commented on Source/GSAudioPlayer.m
> +  _audioFrame = av_frame_alloc();
Added checks.

2025-09-04 13:53 UTC, gcasa commented on Source/GSAudioPlayer.m
> +  snprintf(bufferSizeStr, sizeof(bufferSizeStr), "%d", bufferSize);
Removed

2025-09-04 13:56 UTC, gcasa commented on Source/GSAudioPlayer.m
> +		dict = RETAIN([_audioPackets objectAtIndex: 0]);
Done.

2025-09-04 14:12 UTC, gcasa commented on Source/NSMovie.m
> +  return [self initWithData: movie];
I wasn't sure how to handle this one.  Given that we really don't know what the pointer being passed in is.  I felt as though it was safer to just treat it like an NSData.

2025-09-12 17:30 UTC, gcasa commented
@rfm Please take a look at this one as well.

2025-09-15 15:25 UTC, gcasa commented
I think this is as close to done as I can get it.  It works.  I would like others to have the opportunity to look at and fix the code on this.  Please review and approve if you can @rfm or @fredkiefer

2025-09-24 21:58 UTC, gcasa commented
I think this PR is ready as well, @fredkiefer / @rfm

2025-10-02 02:04 UTC, gcasa commented
@fredkiefer can you take one final look at this.  I really have taken this as far as I can.  It's not perfect, but it works.  I would like to merge this so that others can inspect and improve the code.

2025-10-04 15:54 UTC, gcasa commented
Unless there is an objection I am going to merge this.  I have taken it as far as I can.  I want more people to be able to test it and improve it.

2025-10-04 18:52 UTC, fredkiefer commented
Just give me a few more hours. I am planing of doing a final review of this code tonight.

2025-10-05 03:04 UTC, gcasa commented
Okay. I didn't mean to rush you. I just wanted others to be able to take advantage of it.

2025-10-05 22:26 UTC, fredkiefer reviewed
I don't quite like the concepts behind the current implementation, but I don't see much harm in it. If you really want to, you may go ahead and merge this.

2025-10-05 22:26 UTC, fredkiefer commented on Headers/AppKit/NSMovie.h
> +/* <title>NSMovie</title>
Why did you remove this star here? Is this something we should change in other files as well?

2025-10-05 22:26 UTC, fredkiefer commented on Source/NSMovie.m
> +  return [self initWithData: movie];
I think you are wrong here. The pointer will most likely point to raw movie data, in Apples case a QTMovie. I am unsure how we should handle that. Maybe leave it unimplemented as it was?

2025-10-05 22:26 UTC, fredkiefer commented on Source/GSMovieView.m
> +      return [GSMovieView allocWithZone: zone];
I would prefer an implementation  where we don't subclass NSMovieView. That way we could have different decoder alongside each other.

2025-10-05 22:26 UTC, fredkiefer commented on Source/GSMovieView.m
> +  NSBitmapImageRep *bitmap = [[NSBitmapImageRep alloc]
Here we should try to avoid generating a new NSImage and NSBitmapImageRep for each frame. Or at least avoid the `memcpy`by providing `rgbData` as the first parameter to this method call.

2025-10-05 22:39 UTC, gcasa commented on Source/NSMovie.m
> +  return [self initWithData: movie];
Actually, I think you're right on this one.

2025-10-05 22:41 UTC, gcasa commented on Headers/AppKit/NSMovie.h
> +/* <title>NSMovie</title>
No, this was a mistake.

2025-10-06 02:44 UTC, gcasa commented on Source/GSMovieView.m
> +      return [GSMovieView allocWithZone: zone];
Well, the way it is implemented it uses avcodec which supports a ton of decoders.   I have considered moving support for the movie playing either to the backend or into a separate bundle, but I am not sure.

2025-10-06 02:46 UTC, gcasa commented
Merging this with fred's okay.  Everyone please test this and let me know what I have done wrong with decoding, if anything or how I can improve my approach.

2025-10-06 02:46 UTC, merged