Implement various trivial methods required by GitUp
gnustep/libs-gui pull request #240
Opened 2024-02-05 18:48 UTC by ethanc8

There are a bunch of methods and enums that are needed by GitUp (and probably a lot of other modern apps) that I have implemented in these commits. I think some issues appeared while rebasing the commits on master, though, so these commits might need to be changed.

Additionally, this adds a bunch of renamed enums (Apple has renamed a lot of enums to allow the Swift bridging generator to automatically parse the enum names).

2024-02-05 20:23 UTC, fredkiefer commented on Headers/AppKit/NSView.h
> +@class NSAppearance;
You probably don't need both the import and the class declaration.

2024-02-05 20:25 UTC, fredkiefer commented on Headers/AppKit/NSAlert.h
> +  DEFINE_BLOCK_TYPE(GSNSWindowDidEndSheetCallbackBlock, void, NSModalResponse returnCode);
Shouldn't we reuse the type and block type you define in NSWindow.h here?

2024-02-05 20:26 UTC, fredkiefer commented on Headers/AppKit/NSApplication.h
> +  typedef NSInteger NSModalResponse;
Looks like this is the third place where you define this type.

2024-02-05 20:30 UTC, fredkiefer commented on Source/NSApplication.m
> +  if(_appearance) return _appearance;
We prefer:
`if (_appearance)
{
   return _appearance;
}`

2024-02-05 20:33 UTC, fredkiefer commented on Source/NSView.m
> -/**
This looks like an error. You seem to have removed all the layout code that was added last year.

2024-02-05 20:35 UTC, fredkiefer requested changes
Thank you for this great addition. What worries me is that the layout changes seem to have been lost. Could you please have a look at that?

2024-02-05 22:06 UTC, ethanc8 commented
@fredkiefer I believe I've implemented the changes you've requested. Is there anything else I need to do?

2024-02-06 07:49 UTC, fredkiefer approved these changes
Looks great now!

2024-02-09 04:41 UTC, gcasa commented
There are some issues with your changes regarding @property in NSAppearance.  Please correct these before merging.

2024-02-09 05:18 UTC, ethanc8 commented
> There are some issues with your changes regarding `@property` in NSAppearance. Please correct these before merging.

@gcasa I see that I've forgotten to implement these properties. I might have accidentally removed that when I rebased on the current master. Are there any issues in the header file?

2024-02-09 05:21 UTC, ethanc8 commented
[From the GCC CI runner](https://github.com/gnustep/libs-gui/actions/runs/7791417046/job/21260786141?pr=240):
```
In file included from ../Headers/AppKit/NSView.h:37,
                 from Functions.m:44:
../Headers/AppKit/NSAppearance.h:89:11: error: unknown property attribute ‘strong’
   89 | @property(strong) NSAppearance* appearance;
      |           ^~~~~~
../Headers/AppKit/NSAppearance.h:89:33: warning: object property ‘appearance’ has no ‘assign’, ‘retain’ or ‘copy’ attribute; assuming ‘assign’
   89 | @property(strong) NSAppearance* appearance;
      | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
../Headers/AppKit/NSAppearance.h:89:33: note: ‘assign’ can be unsafe for Objective-C objects; please state explicitly if you need it
../Headers/AppKit/NSAppearance.h:93:21: error: unknown property attribute ‘strong’
   93 | @property(readonly, strong) NSAppearance* effectiveAppearance;
      |                     ^~~~~~
```
@gcasa Is there a macro that shows whether `@property(strong)` is supported by the compiler, or should I just detect clang?

2024-02-09 06:34 UTC, ethanc8 commented
> Is there a macro that shows whether `@property(strong)` is supported by the compiler, or should I just detect clang?
[The clang docs](https://clang.llvm.org/docs/AutomaticReferenceCounting.html#property-declarations) imply that `@property(retain)` and `@property(strong)` are equivalent, and GCC supports `@property(retain)`, so I'll just use that. I've added some notes about it [to my Objective-C documentation project](https://ethanc8.github.io/NewDocumentation-ObjectiveC/Reference/Properties.html#property-attributes) ([source](https://github.com/ethanc8/NewDocumentation-ObjectiveC/blob/master/source/Reference/Properties.md))

2024-02-10 16:19 UTC, ethanc8 commented
> > There are some issues with your changes regarding `@property` in NSAppearance. Please correct these before merging.
> 
> @gcasa I see that I've forgotten to implement these properties. I might have accidentally removed that when I rebased on the current master. Are there any issues in the header file?

Oh, these properties are not implemented because they are in a protocol.

2024-02-10 18:17 UTC, fredkiefer commented
On the gcc pipeline, we get this warning:
```
NSView.m:5260:1: warning: incomplete implementation of class ‘NSView’
 5260 | @end
      | ^
NSView.m:5260:1: warning: method definition for ‘-setAppearance:’ not found
NSView.m:5260:1: warning: method definition for ‘-appearance’ not found
NSView.m:5260:1: warning: method definition for ‘-effectiveAppearance’ not found
NSView.m:5260:1: warning: class ‘NSView’ does not fully implement the ‘NSAppearanceCustomization’ protocol
```

2024-02-10 18:27 UTC, ethanc8 commented
> On the gcc pipeline, we get this warning:
> 
> ```
> NSView.m:5260:1: warning: incomplete implementation of class ‘NSView’
>  5260 | @end
>       | ^
> NSView.m:5260:1: warning: method definition for ‘-setAppearance:’ not found
> NSView.m:5260:1: warning: method definition for ‘-appearance’ not found
> NSView.m:5260:1: warning: method definition for ‘-effectiveAppearance’ not found
> NSView.m:5260:1: warning: class ‘NSView’ does not fully implement the ‘NSAppearanceCustomization’ protocol
> ```
> 
> For clang we get:
> 
> ```
>  Compiling file NSView.m ...
> NSView.m:132:17: warning: auto property synthesis will not synthesize property 'appearance' declared in protocol 'NSAppearanceCustomization' [-Wobjc-protocol-property-synthesis]
> @implementation NSView
>                 ^
> ../Headers/AppKit/NSAppearance.h:89:33: note: property declared here
> @property(retain) NSAppearance* appearance;
>                                 ^
> NSView.m:5260:1: note: add a '@synthesize' directive
> @end
> ^
> NSView.m:132:17: warning: auto property synthesis will not synthesize property 'effectiveAppearance' declared in protocol 'NSAppearanceCustomization' [-Wobjc-protocol-property-synthesis]
> @implementation NSView
>                 ^
> ../Headers/AppKit/NSAppearance.h:93:43: note: property declared here
> @property(readonly, retain) NSAppearance* effectiveAppearance;
>                                           ^
> NSView.m:5260:1: note: add a '@synthesize' directive
> @end
> ^
> 2 warnings generated.
> ```

@fredkiefer I believe [9202dfe](https://github.com/gnustep/libs-gui/pull/240/commits/9202dfeece79b2c2904967e8438bf8601798e8bd) solves this, but I'm not sure if my implementation of `-effectiveAppearance` is correct. Also, is it correct to use `ASSIGN` or `ASSIGNCOPY` in `-setAppearance:`?

2024-02-10 21:10 UTC, gcasa commented
Given @fredkiefer 's approval and that CI is passing I will go ahead and merge this.  @ethanc8 for future reference, when you get approval it is okay for you to go ahead and do the merge so long as CI is passing as well.

2024-02-10 21:10 UTC, merged